### ISSUE TITLE
UI Exception: Could not initialize class java.awt.GraphicsEnvironment$LocalGE

### ISSUE THREAD

**Issue by qts8n** [rycus86/docker-intellij-idea#11]
#### Some Linux users may face `java.lang.NoClassDefFoundError` being thrown while running a container. 

**Please add a warning about this in README**, thank you :)

Error should look something like this:

```
java.lang.NoClassDefFoundError: Could not initialize class java.awt.GraphicsEnvironment$LocalGE
```

Well, actually, it is rather simple to solve this issue. See, when you are running a graphical application on any linux distro, it most definitely will try to create a connection to the X server. But in some cases there will be a security extension called [Xsecurity](https://www.x.org/releases/X11R7.7/doc/man/man7/Xsecurity.7.xhtml) and it will try to prevent such behavior by default.

**To allow your containers to connect to the X server you'll need to use another X utility called `xhost`.** But first you want to install it if you don't have one. Find a package name with this utility on your distro's repositories *(e.g.: on Arch-based distros it will be in `xorg-xhost` package)*. Then use it to allow all local connections:

```bash
xhost +local:
```
Or just allow them to a root user only:

```bash
xhost +si:localuser:root
```

**Comment by rycus86** [comment]
Excellent point! Would you want to open a PR to fix up the README?
