### ISSUE TITLE
Config path '/home/developer/.IdeaIC2018.2/config' is invalid

### ISSUE THREAD

**Issue by fedorenchik** [rycus86/docker-intellij-idea#3]
Error when running this image:

Run with this command:
`$ docker run -e DISPLAY=${DISPLAY} -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/.Idea:/home/developer/.Idea -v ~/.Idea.java:/home/developer/.java -v ~/.Idea.maven:/home/developer/.m2 -v ~/.Idea.gradle:/home/developer/.gradle -v ~/.IdeaIC2018.2:/home/developer/.IdeaIC2018.2 -v ~/elephantrobotics/src/cat/jcat:/home/developer/jcat --name intellij-idea-elephant-jcat rycus86/intellij-idea:2018.2.4`

Output:
```
Invalid Config Path: Config path '/home/developer/.IdeaIC2018.2/config' is invalid.

If you have modified the 'idea.config.path' property, please make sure it is correct,
otherwise please re-install the IDE.
```

And container exits with exit code 5.
```

$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

**Comment by rycus86** [comment]
Hi @fedorenchik ,

The `~/.IdeaIC2018.2` path is symlinked to `~/.Idea`, maybe that is tripping up the config?
If it's not that, then maybe it doesn't have permissions to write that folder, in which case add write permissions to other users, or just do a `chmod 777` on the directory,

If it helps, this is how I run it:

```bash
#!/bin/bash
docker run --rm \
  --network=host \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.Idea:/home/developer/.Idea \
  -v ~/.Idea.java:/home/developer/.java \
  -v ~/.Idea.maven:/home/developer/.m2 \
  -v ~/.Idea.gradle:/home/developer/.gradle \
  -v ~/Project:/home/developer/Project \
  --name idea \
rycus86/intellij-idea
```

**Comment by stefaca** [comment]
All of 4 dirs are made but error is still present.

**Comment by rycus86** [comment]
Can you try a `chmod 777` or `chown <your-user>` on the host folders?

**Comment by stefaca** [comment]
My bad. I didn't know that docker-compose up as a user will create mounted dirs with root:root ownership. Yes, changing ownership to user:group solved issue.
