### ISSUE TITLE
mapping /etc in container to host

### ISSUE THREAD

**Issue by handsomeyang** [rycus86/docker-intellij-idea#4]
If I add "-v ~/etc:/etc" to the docker run command, IDEA will be looking at the "?" folder in the current WORKDIR for configrations. Any idea? Thanks.

The console messages are:
---------------------------------------------------------
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Fontconfig error: Cannot load default config file
Jul 30, 2019 9:14:14 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Jul 30, 2019 9:14:14 AM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background ?/.java/.userPrefs/prefs.xml
Fontconfig error: Cannot load default config file

**Comment by rycus86** [comment]
Not sure what are the contents of the `etc` folder under your home directory at `~/etc`, but mapping that to the root `/etc` seems to break some assumptions about the underlying system.
What are you trying to achieve? Did you mean to map that user folder to that system folder?

**Comment by handsomeyang** [comment]
I am trying to persist system configurations of the container to host.

**Comment by rycus86** [comment]
I think you're after `-v ~/.Idea:/home/developer/.Idea` and `-v ~/.Idea.java:/home/developer/.java` as shown in https://github.com/rycus86/docker-intellij-idea/blob/master/README.md#usage

Does setting those volume mounts help?

**Comment by handsomeyang** [comment]
Other than IDEA and Java configurations, I am also interested in configurations of the system itself and its installed packages, thus the /etc folder.

**Comment by rycus86** [comment]
That might be tricky as `-v *:/etc` will "overwrite" the contents of `/etc` as the container sees it with what on your host folder (probably empty). The original files and configuration come from the Dockerfile and the base image.
Is there something in particular you're after or are investigating?

**Comment by handsomeyang** [comment]
Yes, I am trying to set up a one-container Java development environment based on your Dockerfile. The environment requires additional packages such as Redis, RabbitMq, MySQL, etc. I use "RUN apt-get install" to install those packages. Now I want to persist the configurations and data of those packages to maintain the "development session".

I am guessing mounting the whole /etc folder is causing the problem while mounting individual files and subfolders of /etc will be OK?

**Comment by rycus86** [comment]
Right. In that case you should have a Dockerfile that uses my image as `FROM rycus86/intellij-idea:2019.2` then add the packages with `RUN apt-get` as you said. For the configuration and data though, you'll have to declare a `VOLUME` for each of those folders, and they'll be application specific, so may be a bit hard to track them down.

> I am guessing mounting the whole /etc folder is causing the problem while mounting individual files and subfolders of /etc will be OK?

Yes, exactly. If you can mount only some subfolders where the config/data lives for the apps you need, that could potentially work

**Comment by handsomeyang** [comment]
Thanks.

Got one question for your Dockerfile though. What does the following line do?
`RUN mkdir /home/developer/.Idea \
  && ln -sf /home/developer/.Idea /home/developer/$idea_local_dir`
I think you are trying to make a symbolic link named ".Idea" to the IDEA configuration folder. Shouldn't it be the other way around? like 
`ln -sf /home/developer/$idea_local_dir /home/developer/.Idea`

**Comment by rycus86** [comment]
It is like this so that you can mount with `-v` to the `/home/developer/.Idea` path to keep the config, rather than to work out the folder name based on the IntelliJ version number.
